name: Generate snake contribution graph

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Sanketk-1154
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Push generated SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
